language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - tip

env:
  - DEP_VERSION="0.3.2"

before_script:
  # - go get github.com/golang/lint/golint/...
  - go vet ./bankinfo \
    ./charset \
    ./client \
    ./cmd/... \
    ./crypto \
    ./dialog \
    ./domain \
    ./element \
    ./generator \
    ./iban \
    ./internal \
    ./message \
    ./segment \
    ./swift \
    ./token \
    ./transport
  # - golint -set_exit_status bankinfo \
  # charset \
  # client \
  # cmd \
  # crypto \
  # dialog \
  # domain \
  # element \
  # generator \
  # hbci.go \
  # iban \
  # internal \
  # message \
  # segment \
  # swift \
  # token \
  # transport

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
