language: go

go:
  - 1.9
  - "1.10"
  - tip

env:
  - DEP_VERSION="0.3.2"
  - CC_TEST_REPORTER_ID=c5541b7f3112815fc1a3cb4b4c67b4bf6f3efc89c2109bd96530e1bffd7d20d6

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /usr/local/bin/cc-test-reporter
  - chmod +x /usr/local/bin/cc-test-reporter
  - cc-test-reporter before-build
  - go get github.com/golang/lint/golint/...
  - go vet ./bankinfo ./charset ./client ./cmd/... ./crypto ./dialog ./domain ./element ./generator ./iban ./internal ./message ./segment ./swift ./token ./transport
  - golint -set_exit_status bankinfo charset client cmd dialog domain element generator iban internal message #segment swift token transport

after_script:
  - cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
